modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="RZY"
description='''感谢您的游玩'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="parcool"
mandatory=true
versionRange="[3.4.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tacz"
mandatory=true
versionRange="[1.1.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sound_physics_remastered"
mandatory=false
versionRange="[1,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="${mod_id}.mixins.json"
