modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="dealt_force_skills"
version="${mod_version}"
displayName="dealt_force_skills"
authors="RZY"
description='''感谢您的游玩'''

[[dependencies.dealt_force_skills]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dealt_force_skills]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.dealt_force_skills]]
modId="parcool"
mandatory=true
versionRange="[3.4.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dealt_force_skills]]
modId="tacz"
mandatory=false
versionRange="[1.1.5,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="dealt_force_skills.mixins.json"
